# Electric Vehicle Presence Discovery

## Import Packages

In [2]:
import datetime as dat
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pylab
import scipy.stats as stats

In [6]:
#import data from pickle file
df = pd.read_pickle('Data/raw_data.pkl')

In [7]:
df.shape

(5556701, 6)

In [8]:
list(df)

['dataid', 'localhour', 'use', 'car1', 'gen', 'grid']

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
dataid,5556701.0,5149.901509,3005.414069,59.00000,2472.000000,5218.000000,7875.000000,9983.000000
use,5411099.0,1.321350,1.413085,0.00000,0.431383,0.835383,1.705417,35.877467
car1,1133780.0,0.216458,0.970097,0.00000,0.000000,0.000000,0.004933,19.042100
gen,3759762.0,0.693997,1.227411,-5.14115,-0.005500,0.000000,0.903413,12.158517
grid,5379850.0,0.838332,1.665147,-8.44230,0.247067,0.632700,1.403017,29.253183

In [10]:
df.isnull().sum()

dataid             0
localhour          0
use           145602
car1         4422921
gen          1796939
grid          176851
dtype: int64

In [11]:
df['localhour'] = pd.to_datetime(df['localhour'], utc=True)

In [12]:
df.dtypes

dataid                     int64
localhour    datetime64[ns, UTC]
use                      float64
car1                     float64
gen                      float64
grid                     float64
dtype: object

In [13]:
df.head()

   dataid                 localhour       use  car1  gen      grid
0      59 2016-01-01 06:00:00+00:00  2.531233   NaN  NaN  2.531233
1      59 2016-01-01 07:00:00+00:00  2.801450   NaN  NaN  2.801450
2      59 2016-01-01 08:00:00+00:00  2.373550   NaN  NaN  2.373550
3      59 2016-01-01 09:00:00+00:00  2.680283   NaN  NaN  2.680283
4      59 2016-01-01 10:00:00+00:00  2.465950   NaN  NaN  2.465950

In [14]:
df.dataid.nunique()

230

In [15]:
df.count()

dataid       5556701
localhour    5556701
use          5411099
car1         1133780
gen          3759762
grid         5379850
dtype: int64

In [16]:
pd.value_counts(df["dataid"].values, sort=True)

7769    26266
8767    26265
3734    26265
499     26265
1192    26265
1202    26265
871     26265
9484    26265
5738    26265
3009    26265
171     26265
6578    26265
5921    26265
5035    26265
8243    26265
821     26265
4633    26265
994     26264
7504    26264
1086    26264
9356    26264
9141    26264
8236    26264
2953    26264
9647    26264
5784    26264
9983    26264
1792    26264
2004    26264
6148    26264
        ...
4526    21242
2018    20855
6348    20535
77      19235
516     18797
4874    18305
3918    18114
9613    17524
6643    16990
2365    16509
1283    16489
7390    16190
9631    15227
7793    15131
3044    14470
6799    13646
1629    12582
3635    12386
6692    12032
4499    11131
9248    10449
4732    10147
4956     9198
9926     9178
1589     8322
1617     8261
5371     8098
698      7348
9958     6949
4296     3193
Length: 230, dtype: int64

In [17]:
maxtime = max(df['localhour'])
mintime = min(df['localhour'])
print(maxtime, mintime)

2018-12-31 06:00:00+00:00 2016-01-01 06:00:00+00:00

In [18]:
df.groupby('dataid')['localhour'].max()

dataid
59     2018-12-31 06:00:00+00:00
77     2018-07-12 09:00:00+00:00
86     2018-12-31 06:00:00+00:00
93     2018-12-31 06:00:00+00:00
94     2018-12-31 06:00:00+00:00
114    2018-12-31 06:00:00+00:00
171    2018-12-31 06:00:00+00:00
232    2018-12-31 06:00:00+00:00
252    2018-12-31 06:00:00+00:00
370    2018-12-31 06:00:00+00:00
379    2018-12-31 06:00:00+00:00
499    2018-12-31 06:00:00+00:00
503    2018-12-03 11:00:00+00:00
516    2018-12-31 06:00:00+00:00
547    2018-12-31 06:00:00+00:00
668    2018-12-31 06:00:00+00:00
698    2018-12-31 06:00:00+00:00
744    2018-12-31 06:00:00+00:00
781    2018-12-31 06:00:00+00:00
796    2018-12-31 06:00:00+00:00
821    2018-12-31 06:00:00+00:00
871    2018-12-31 06:00:00+00:00
890    2018-12-31 06:00:00+00:00
946    2018-12-31 06:00:00+00:00
974    2018-12-31 06:00:00+00:00
994    2018-12-31 06:00:00+00:00
1086   2018-12-31 06:00:00+00:00
1103   2018-12-31 06:00:00+00:00
1169   2018-12-31 06:00:00+00:00
1185   2018-12-31 06:00:00+00:00
                  ...
9052   2018-12-31 06:00:00+00:00
9121   2018-12-31 06:00:00+00:00
9134   2018-12-31 06:00:00+00:00
9141   2018-12-31 06:00:00+00:00
9206   2018-12-31 06:00:00+00:00
9248   2017-03-11 14:00:00+00:00
9295   2018-12-31 06:00:00+00:00
9333   2018-12-31 06:00:00+00:00
9356   2018-12-31 06:00:00+00:00
9484   2018-12-31 06:00:00+00:00
9609   2018-12-31 06:00:00+00:00
9613   2017-12-31 23:00:00+00:00
9631   2018-12-31 06:00:00+00:00
9647   2018-12-31 06:00:00+00:00
9701   2018-12-31 06:00:00+00:00
9737   2018-12-31 06:00:00+00:00
9776   2018-12-31 06:00:00+00:00
9818   2018-12-31 06:00:00+00:00
9875   2018-12-31 06:00:00+00:00
9915   2018-12-31 06:00:00+00:00
9926   2018-12-31 06:00:00+00:00
9932   2018-12-31 06:00:00+00:00
9934   2018-12-31 06:00:00+00:00
9935   2018-12-31 06:00:00+00:00
9938   2018-12-31 06:00:00+00:00
9939   2018-12-31 06:00:00+00:00
9942   2018-12-31 06:00:00+00:00
9958   2018-12-31 06:00:00+00:00
9971   2018-12-31 06:00:00+00:00
9983   2018-12-31 06:00:00+00:00
Name: localhour, Length: 230, dtype: datetime64[ns, UTC]

In [19]:
df.groupby('dataid')['localhour'].min()

dataid
59     2016-01-01 06:00:00+00:00
77     2016-01-01 06:00:00+00:00
86     2016-01-01 06:00:00+00:00
93     2016-01-01 06:00:00+00:00
94     2016-01-01 06:00:00+00:00
114    2016-01-01 06:00:00+00:00
171    2016-01-01 06:00:00+00:00
232    2016-01-01 06:00:00+00:00
252    2016-01-01 06:00:00+00:00
370    2016-01-01 06:00:00+00:00
379    2016-01-01 06:00:00+00:00
499    2016-01-01 06:00:00+00:00
503    2016-01-01 06:00:00+00:00
516    2016-01-01 06:00:00+00:00
547    2016-01-01 06:00:00+00:00
668    2016-01-01 06:00:00+00:00
698    2017-07-29 07:00:00+00:00
744    2016-01-01 06:00:00+00:00
781    2016-01-01 06:00:00+00:00
796    2016-01-01 06:00:00+00:00
821    2016-01-01 06:00:00+00:00
871    2016-01-01 06:00:00+00:00
890    2016-01-01 06:00:00+00:00
946    2016-01-01 06:00:00+00:00
974    2016-01-01 06:00:00+00:00
994    2016-01-01 06:00:00+00:00
1086   2016-01-01 06:00:00+00:00
1103   2016-01-01 06:00:00+00:00
1169   2016-01-01 06:00:00+00:00
1185   2016-07-15 05:00:00+00:00
                  ...
9052   2016-01-01 06:00:00+00:00
9121   2016-01-01 06:00:00+00:00
9134   2016-01-01 06:00:00+00:00
9141   2016-01-01 06:00:00+00:00
9206   2016-01-06 18:00:00+00:00
9248   2016-01-01 06:00:00+00:00
9295   2016-01-01 06:00:00+00:00
9333   2016-01-01 06:00:00+00:00
9356   2016-01-01 06:00:00+00:00
9484   2016-01-01 06:00:00+00:00
9609   2016-01-01 06:00:00+00:00
9613   2016-01-01 06:00:00+00:00
9631   2016-01-01 06:00:00+00:00
9647   2016-01-01 06:00:00+00:00
9701   2016-01-01 06:00:00+00:00
9737   2016-01-01 06:00:00+00:00
9776   2016-01-01 06:00:00+00:00
9818   2016-01-01 06:00:00+00:00
9875   2016-01-01 06:00:00+00:00
9915   2016-01-01 06:00:00+00:00
9926   2016-01-01 06:00:00+00:00
9932   2016-01-01 06:00:00+00:00
9934   2016-01-01 06:00:00+00:00
9935   2016-01-01 06:00:00+00:00
9938   2016-01-01 06:00:00+00:00
9939   2016-01-01 06:00:00+00:00
9942   2016-01-01 06:00:00+00:00
9958   2016-01-01 06:00:00+00:00
9971   2016-01-01 06:00:00+00:00
9983   2016-01-01 06:00:00+00:00
Name: localhour, Length: 230, dtype: datetime64[ns, UTC]

In [20]:
df.groupby('dataid').describe()

            use                                                              \
          count      mean       std       min       25%       50%       75%
dataid
59      26264.0  1.752956  1.377223  0.321167  0.687171  1.282692  2.463758
77      19235.0  1.638684  1.223294  0.282767  0.709708  1.241883  2.231708
86      26256.0  1.495249  1.253516  0.000000  0.508312  1.057083  2.069796
93      26262.0  1.051423  1.090478  0.000000  0.400983  0.534792  1.248286
94      26198.0  0.691208  0.494313  0.000000  0.320562  0.531858  0.909312
114     26262.0  1.265242  1.047018  0.000000  0.552046  0.879600  1.637279
171     26265.0  0.867947  0.780580  0.128250  0.338583  0.572967  1.069900
232     25779.0  0.934163  0.742652  0.221967  0.530875  0.697167  0.998858
252     26072.0  2.981845  1.525306  0.389217  1.847779  2.575842  3.786942
370     26263.0  1.465269  1.200093  0.335183  0.664033  1.013617  1.738833
379     26263.0  1.783553  1.626741  0.269683  0.698833  1.254967  2.237475
499     26265.0  1.353682  0.592910  0.012000  0.910917  1.198367  1.675817
503     24743.0  1.490968  1.222694  0.002000  0.646583  0.999850  1.875217
516     18797.0  0.744477  0.542311  0.182017  0.401617  0.560950  0.925050
547     26175.0  1.741348  1.792776  0.010000  0.618575  1.173750  2.078033
668     25836.0  1.356897  0.976562  0.067733  0.627212  1.068892  1.817067
698      7348.0  1.486896  0.692667  0.692883  1.013562  1.220017  1.737533
744     26264.0  1.137959  1.127275  0.151083  0.283996  0.592925  1.640437
781     26244.0  1.245703  1.015082  0.096383  0.466242  0.844317  1.809283
796         0.0       NaN       NaN       NaN       NaN       NaN       NaN
821     26265.0  0.640253  0.562059  0.003000  0.280833  0.397467  0.800650
871     26265.0  0.848239  0.772318  0.000000  0.367650  0.535933  1.030983
890     21888.0  1.074643  0.944500  0.117650  0.430208  0.701083  1.382779
946     26258.0  0.716498  0.656725  0.116467  0.279421  0.409400  0.949496
974     26241.0  1.989379  1.582090  0.256667  0.802867  1.356700  2.716733
994     26264.0  0.847250  0.831017  0.130733  0.361017  0.463717  0.940642
1086    26264.0  0.984821  0.698745  0.000000  0.521312  0.694842  1.190817
1103    26263.0  0.620675  0.688443  0.194967  0.248767  0.276000  0.672900
1169    26217.0  0.902436  0.797244  0.211817  0.431917  0.603783  1.033033
1185    14458.0  1.819574  1.690362  0.000000  0.610504  1.160533  2.436700
...         ...       ...       ...       ...       ...       ...       ...
9052    26201.0  1.204782  1.053944  0.208633  0.410800  0.822450  1.601117
9121    26241.0  1.154581  1.069644  0.141633  0.361667  0.704067  1.598950
9134    26244.0  1.456436  0.821880  0.701850  0.871029  1.181715  1.698287
9141    25600.0  1.087934  1.185636  0.000000  0.249958  0.547375  1.595583
9206    26132.0  2.302155  1.711977  0.223500  1.093642  1.787900  3.155946
9248    10449.0  2.213064  1.611958  0.341850  0.877617  1.784400  3.055783
9295    23666.0  1.311128  1.162704  0.275667  0.624896  0.901333  1.469925
9333    26263.0  1.741339  1.290211  0.006000  0.757100  1.361317  2.341150
9356    26264.0  2.172674  1.442553  0.000000  1.058942  1.843025  2.933525
9484    26265.0  2.315414  1.300213  0.017000  1.321217  1.975550  2.974300
9609    26261.0  1.091847  1.041468  0.000000  0.350483  0.700533  1.461600
9613    17524.0  1.111988  1.062459  0.001000  0.295342  0.720333  1.589121
9631    15227.0  1.222392  1.052894  0.146850  0.436125  0.853283  1.695400
9647    26264.0  3.046630  2.436290  0.233450  1.176067  2.373317  4.422875
9701    26165.0  0.307128  0.324197  0.000000  0.116300  0.176517  0.354150
9737    22196.0  2.783993  2.204705  0.418517  1.084846  1.979350  3.825380
9776    26263.0  3.324808  2.555496  0.012000  1.368792  2.616333  4.461742
9818    23465.0  0.939466  0.969144  0.106233  0.351667  0.625867  1.072300
9875    24288.0  1.218550  1.024517  0.000000  0.441333  0.815175  1.823179
9915    21394.0  0.828923  0.867670  0.000000  0.236279  0.451900  1.074346
9926     9115.0  1.094277  0.721468  0.371400  0.595550  0.865300  1.290092
9932    26263.0  0.685301  0.639130  0.000000  0.360975  0.453683  0.741892
9934    23985.0  1.250535  1.269529  0.040733  0.408709  0.784117  1.565567
9935    26124.0  6.188534  5.165898  0.001000  2.619754  4.523034  7.890754
9938    13463.0  1.934022  1.092840  0.354783  1.051625  1.636750  2.576825
9939    20905.0  1.365965  0.877917  0.120429  0.755417  1.039800  1.619167
9942    25592.0  1.165591  0.854753  0.000000  0.485196  0.933483  1.558604
9958     6949.0  0.460318  0.346949  0.138767  0.221417  0.321250  0.576600
9971    26244.0  0.768670  1.549154  0.109000  0.214413  0.275217  0.400271
9983    26264.0  1.616657  1.619746  0.005000  0.550625  0.881492  2.078000

                      car1            ...       gen                grid  \
              max    count      mean  ...       75%        max    count
dataid                                ...
59      10.690317      0.0       NaN  ...  0.000000   0.000000  26264.0
77       9.144567      0.0       NaN  ...  0.807708   2.853917  19235.0
86      10.514386      0.0       NaN  ...  0.000000   0.000000  26256.0
93       6.443333      0.0       NaN  ...  1.222000   5.272683  26262.0
94       4.719500      0.0       NaN  ...  0.000000   0.000000  26198.0
114      7.977350  26263.0  0.150572  ...  0.908717   3.007517  26262.0
171      6.698367      0.0       NaN  ...  1.347983   4.930600  26265.0
232      6.983717      0.0       NaN  ...  0.000000   0.000000  25779.0
252     10.229250      0.0       NaN  ...  1.295454   4.187317  26072.0
370      8.805617  26263.0  0.269367  ...  1.133300   4.263783  26263.0
379     13.185950  25343.0  0.212305  ...  1.453800   4.933117  26262.0
499      6.618283      0.0       NaN  ...  0.731900   3.628717  26265.0
503      8.446850      0.0       NaN  ...  0.000000   0.000000  24743.0
516      7.267067      0.0       NaN  ...  0.000000   0.000000  18797.0
547     15.778583  26175.0  0.284593  ...  0.555317   4.227450  26175.0
668      7.059617      0.0       NaN  ...  1.419317   5.134183  25836.0
698      6.161633      0.0       NaN  ...  1.215863   4.930533   7348.0
744      5.679583      0.0       NaN  ...  1.100942   3.788267  26264.0
781      7.048100      0.0       NaN  ...  1.619553   4.880617  26243.0
796           NaN  21447.0  0.156346  ...       NaN        NaN      0.0
821      5.044383      0.0       NaN  ...  0.000000   0.000000  26265.0
871      7.159950      0.0       NaN  ...  0.000000   0.000000  26265.0
890      8.635583      0.0       NaN  ...  0.852533   3.908350  21888.0
946      3.774017      0.0       NaN  ...  0.000000   0.000000  26101.0
974     11.054717      0.0       NaN  ...  1.782067   8.836033  26241.0
994      6.769017      0.0       NaN  ...  0.000000   0.000000  26264.0
1086     4.108900      0.0       NaN  ...  0.000000   0.000000  26264.0
1103     4.563433      0.0       NaN  ...  1.028325   3.148367  26263.0
1169     7.011417  26217.0  0.129351  ...  0.953067   3.023350  26216.0
1185    11.931400   9491.0  0.245091  ...  1.604600   5.192467   9491.0
...           ...      ...       ...  ...       ...        ...      ...
9052     7.667617      0.0       NaN  ...  1.500533   4.741417  26201.0
9121     6.865450      0.0       NaN  ...  1.432633   4.782550  26241.0
9134     7.317083      0.0       NaN  ...  1.338645   4.040250  26244.0
9141     8.811583      0.0       NaN  ...  0.000000   0.000000  25600.0
9206    19.535683      0.0       NaN  ...  0.000000   0.000000  26132.0
9248     9.729883      0.0       NaN  ...  0.379881   1.392567  10449.0
9295    12.094500      0.0       NaN  ...  0.000000   0.000000  23885.0
9333     9.635067      0.0       NaN  ...  0.000000   0.000000  26263.0
9356    10.971450      0.0       NaN  ...  0.000000   0.000000  26264.0
9484     9.734467  26265.0  0.002397  ...  0.000000   0.000000  26265.0
9609     7.128383  26261.0  0.143727  ...  0.000000   0.000000  26261.0
9613     6.730150      0.0       NaN  ...       NaN        NaN  17524.0
9631     8.071500      0.0       NaN  ...  1.154325   3.754850  15227.0
9647    18.980250  26255.0  0.195244  ...  1.764296   5.711717  26255.0
9701     3.741000      0.0       NaN  ...  0.000000   0.000000  26165.0
9737    14.403333      0.0       NaN  ...  1.943679   8.193183  22196.0
9776    21.425650  26263.0  0.223569  ...  1.474608   5.711467  26263.0
9818     7.864450      0.0       NaN  ...  0.000000   0.000000  23465.0
9875     6.424833      0.0       NaN  ...  0.000000   0.000000  24288.0
9915     6.330000      0.0       NaN  ...  0.000000   0.000000  20997.0
9926     6.888950      0.0       NaN  ...       NaN        NaN   9115.0
9932    10.633150  26263.0  0.030743  ...  1.003725   4.199650  26263.0
9934    11.882778  23985.0  0.247535  ...  0.025276   7.679857  23985.0
9935    35.877467  26124.0  0.098968  ...  0.011953  12.158517  26124.0
9938     7.486517      0.0       NaN  ...       NaN        NaN  13463.0
9939     7.013400      0.0       NaN  ...  0.958600   3.518350  20905.0
9942     5.410017      0.0       NaN  ...  0.103992   0.431600  25592.0
9958     3.506383      0.0       NaN  ...  0.000000   0.000000   6949.0
9971    19.461183      0.0       NaN  ...  1.572163   4.986500  26244.0
9983    10.455117      0.0       NaN  ...  0.000000   0.000000  26264.0


            mean       std       min       25%       50%       75%        max
dataid
59      1.752956  1.377223  0.321167  0.687171  1.282692  2.463758  10.690317
77      1.149250  1.268230 -2.382117  0.466533  0.887083  1.702183   8.841783
86      1.495249  1.253516  0.000000  0.508312  1.057083  2.069796  10.514386
93      0.279810  1.749851 -4.705700 -0.411575  0.414258  1.092625   6.407551
94      0.691208  0.494313  0.000000  0.320562  0.531858  0.909312   4.719500
114     0.728641  1.350517 -2.788083  0.162596  0.690967  1.298450   7.973150
171     0.042998  1.287765 -4.653967 -0.402650  0.331083  0.685583   6.385483
232     0.934163  0.742652  0.221967  0.530875  0.697167  0.998858   6.983717
252     2.226182  1.626301 -3.366400  1.365304  2.147800  3.061400   9.811300
370     0.760938  1.349824 -3.514067  0.390333  0.674533  1.167275   8.777917
379     0.855038  2.125785 -4.572750  0.057275  0.828625  1.665162  12.444500
499     0.790739  0.991793 -2.835050  0.529450  0.912317  1.344550   6.186817
503     1.490968  1.222694  0.002000  0.646583  0.999850  1.875217   8.446850
516     0.744477  0.542311  0.182017  0.401617  0.560950  0.925050   7.267067
547     1.252789  2.079178 -3.633917  0.398592  0.825067  1.832258  15.776333
668     0.480771  1.321825 -4.844583  0.170433  0.631458  1.179912   5.849967
698     0.678299  1.508874 -3.776767  0.220400  1.003050  1.395221   6.130183
744     0.494429  1.536584 -3.489800 -0.205787  0.384667  1.262267   5.685233
781     0.341281  1.767025 -4.600483 -0.652817  0.459950  1.362392   7.048100
796          NaN       NaN       NaN       NaN       NaN       NaN        NaN
821     0.640253  0.562059  0.003000  0.280833  0.397467  0.800650   5.044383
871     0.848239  0.772318  0.000000  0.367650  0.535933  1.030983   7.159950
890     0.448917  1.120385 -3.299033  0.188508  0.417217  0.877667   6.751117
946     0.718351  0.657437  0.116483  0.280400  0.410383  0.953833   3.774017
974     0.930153  2.027987 -7.314583  0.173000  0.907800  1.929350   9.603817
994     0.847250  0.831017  0.130733  0.361017  0.463717  0.940642   6.769017
1086    0.984821  0.698745  0.000000  0.521312  0.694842  1.190817   4.108900
1103    0.036056  1.102958 -2.898317 -0.467042  0.242883  0.441433   4.190500
1169    0.339388  1.191958 -2.789900 -0.071054  0.434692  0.765688   7.016017
1185    0.829426  2.047526 -4.731467  0.122100  0.717750  1.684525  10.868667
...          ...       ...       ...       ...       ...       ...        ...
9052    0.316415  1.512743 -4.383200 -0.145000  0.449017  1.067500   7.225117
9121    0.312046  1.449049 -4.400650 -0.166133  0.373817  0.984183   6.731467
9134    0.694100  1.432230 -3.197583  0.106908  0.870215  1.441229   6.655917
9141    1.087934  1.185636  0.000000  0.249958  0.547375  1.595583   8.811583
9206    2.302155  1.711977  0.223500  1.093642  1.787900  3.155946  19.535683
9248    1.975441  1.617549 -0.902283  0.768867  1.576100  2.791367   9.735433
9295    1.308477  1.161093  0.275667  0.623333  0.899508  1.467085  12.094500
9333    1.741339  1.290211  0.006000  0.757100  1.361317  2.341150   9.635067
9356    2.172674  1.442553  0.000000  1.058942  1.843025  2.933525  10.971450
9484    2.315414  1.300213  0.017000  1.321217  1.975550  2.974300   9.734467
9609    1.091847  1.041468  0.000000  0.350483  0.700533  1.461600   7.128383
9613    1.111988  1.062459  0.001000  0.295342  0.720333  1.589121   6.730150
9631    0.533372  1.332498 -3.508033  0.135275  0.493150  1.100133   6.721317
9647    2.004869  2.582535 -4.950483  0.596175  1.643517  3.302658  17.283167
9701    0.307128  0.324197  0.000000  0.116300  0.176517  0.354150   3.741000
9737    1.524863  3.087406 -7.297400  0.137448  1.316533  3.105878  14.412583
9776    2.356678  2.395599 -4.293150  0.828792  1.702100  3.290492  18.919767
9818    0.939466  0.969144  0.106233  0.351667  0.625867  1.072300   7.864450
9875    1.218550  1.024517  0.000000  0.441333  0.815175  1.823179   6.424833
9915    0.810968  0.850864  0.000000  0.233733  0.443650  1.042517   6.330000
9926    1.094277  0.721468  0.371400  0.595550  0.865300  1.290092   6.888950
9932    0.017111  1.280477 -3.898767 -0.418742  0.361333  0.569392  10.633150
9934    0.605674  2.155605 -7.507000  0.279167  0.699900  1.501412  12.356889
9935    5.709554  4.408840 -0.025900  2.537342  4.389874  7.673831  29.253183
9938    1.934022  1.092840  0.354783  1.051625  1.636750  2.576825   7.486517
9939    0.736121  1.311004 -2.915133  0.294050  0.810133  1.366650   6.600933
9942    1.103014  0.854368 -0.140150  0.432129  0.877983  1.496729   5.409983
9958    0.460318  0.346949  0.138767  0.221417  0.321250  0.576600   3.506383
9971   -0.140303  2.101340 -4.655933 -0.969946  0.178725  0.312421  19.461183
9983    1.616657  1.619746  0.005000  0.550625  0.881492  2.078000  10.455117

[230 rows x 32 columns]

In [24]:
 df = df.groupby('dataid').mean()

In [25]:
fillna = df.fillna(0)
fillna.head()

             use  car1       gen      grid
dataid
59      1.752956   0.0  0.000000  1.752956
77      1.638684   0.0  0.486312  1.149250
86      1.495249   0.0  0.000000  1.495249
93      1.051423   0.0  0.767092  0.279810
94      0.691208   0.0  0.000000  0.691208

In [30]:
#export to csv to store on local drive
df.to_csv('Data/grouped_electricity_data.csv')

In [29]:
fillna.isnull().sum()

use     0
car1    0
gen     0
grid    0
dtype: int64